FORMAT: 1A
HOST: http://www.commonsid.org

# Hash Store
Hash Store is a simple service to store provenance information based on the hashes of media files.

# Group Home

## Home [/]
### Retrieve the entry point [GET]
+ Request (vnd.collection+json)

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.commonsid.org/",
                "links": [
                    {
                        "rel": "works",
                        "href": "http://www.commonsid.org/works",
                        "prompt" : "Works"
                    }
                ]
            }
        }

+ Request (text/html)

+ Response 200 (text/html)

        <ul>
        <li><a href="http://www.commonsid.org/works">Works</a></li>
        </ul>

# Group Work

## Works [/works]
### Retrieve a list of works [GET]
+ Request (vnd.collection+json)

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.commonsid.org/works",
                "items": [
                    {
                        "href": "http://www.commonsid.org/works/03535231",
                        "data": [
                            {
                                "name": "uri",
                                "value": "http://example.com/image.jpg",
                                "prompt": "URI"
                            },
                            {
                                "name": "author",
                                "value": "John Snow",
                                "prompt": "Author"
                            },
                            {
                                "name": "license",
                                "value": "https://creativecommons.org/publicdomain/zero/1.0/",
                                "prompt": "License"
                            },
                            {
                                "name": "sha256",
                                "value": "b241121..",
                                "prompt": "SHA256"
                            },
                            {
                                "name": "md5",
                                "value": "a21342b1..",
                                "prompt": "MD5"
                            }
                        ],
                        "links": [
                            {
                                "rel": "attribution",
                                "href": "http://www.commonsid.org/works/03535231/attribution",
                                "prompt": "Attribution"
                            }
                        ]
                    }
                ],
                "queries": [
                    {
                        "href": "http://www.commonsid.org/works",
                        "rel": "search",
                        "prompt": "Search for a Work",
                        "data": [
                            {
                                "name": "uri",
                                "value": ""
                            },
                            {
                                "name": "author",
                                "value": ""
                            },
                            {
                                "name": "license",
                                "value": ""
                            },
                            {
                                "name": "sha256",
                                "value": ""
                            },
                            {
                                "name": "md5",
                                "value": ""
                            }
                        ]
                    }
                ],
                "template": {
                    "data": [
                        {
                            "name": "uri",
                            "value": "",
                            "prompt": "URL of the Work"
                        },
                        {
                            "name": "author",
                            "value": "",
                            "prompt": "Author of the Work"
                        },
                        {
                            "name": "license",
                            "value": "",
                            "prompt": "Creative Commons License"
                        }
                    ]
                }
            }
        }
        
### Post a new work to the service [POST]
+ Request (vnd.collection+json)

        {
            "template": {
                "data": [
                    {
                        "name": "URI",
                        "value": "http://example.com/image.jpg"
                    },
                    {
                        "name": "Author",
                        "value": "John Snow"
                    },
                    {
                        "name": "License",
                        "value": "https://creativecommons.org/publicdomain/zero/1.0/"
                    }
                ]
            }
        }
        
+ Response 201 (vnd.collection+json)
    + Headers
    
            Location: http://www.commonsid.org/works/03535231
            Content-Location: http://www.commonsid.org/works/03535231

    + Body
    
            {
                "collection": {
                    "version": "1.0",
                    "href": "http://www.commonsid.org/works",
                    "items": [
                        {
                            "href": "http://www.commonsid.org/works/03535231",
                            "data": [
                                {
                                    "name": "uri",
                                    "value": "http://example.com/image.jpg",
                                    "prompt": "URI"
                                },
                                {
                                    "name": "author",
                                    "value": "John Snow",
                                    "prompt": "Author"
                                },
                                {
                                    "name": "license",
                                    "value": "https://creativecommons.org/publicdomain/zero/1.0/",
                                    "prompt": "License"
                                },
                                {
                                    "name": "sha256",
                                    "value": "b241121..",
                                    "prompt": "SHA256"
                                },
                                {
                                    "name": "md5",
                                    "value": "a21342b1..",
                                    "prompt": "MD5"
                                }
                            ],
                            "links": [
                                {
                                    "rel": "attribution",
                                    "href": "http://www.commonsid.org/works/03535231/attribution",
                                    "prompt": "Attribution"
                                }
                            ]
                        }
                    ]
                }
            }


+ Response 400 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.commonsid.org/works",
                "error": {
                    "title": "Source Unavailable",
                    "code": "400",
                    "message": "The specified URI is unreachable or does not exist."
                }
            }
        }
        
# Group Hash retrievel

## Hash retrieval list [/hash]
### Get all hash methods [GET]
+ Response 200 (application/json)

        {
            ["sha0", "sha1", "sha2", "md5", "phash"]
        }

# Group Object Retrievel
## Object Retrieval by hash [/hash/{method}/{hash}]

+ Parameters
    + method (required, string, `sha1`) ... String `method` of the hash method that was used to create `hash`.
    + hash (required, string, `ab324c53b..`) ... String `hash` with method `method`.

### Get all provenance information [GET]
+ Response 200 (application/json)

        {
          "URI": "http://example.com/image.jpg", "Author", "John Snow", "License", "https://creativecommons.org/publicdomain/zero/1.0/"
        }
+ Response 404 (application/json)

        {
            "message" : "No Object at this hash"
        }

# Group Attribution Retrievel
## Object Retrieval by hash [/hash/{method}/{hash}/Attribution]

+ Parameters
    + method (required, string, `sha1`) ... String `method` of the hash method that was used to create `hash`.
    + hash (required, string, `ab324c53b..`) ... String `hash` with method `method`.

### Get all provenance information [GET]
+ Request (application/json)

+ Response 200 (application/json)

        {
          "result": {"URI": "http://example.com/image.jpg", "Author": "John Snow", "License": "https://creativecommons.org/publicdomain/zero/1.0/"}
        }
        
+ Request (text/html)

+ Response 200 (text/html)

        This work by John Snow is licensed under <a rel=license src="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>

+ Request (text/plain)

+ Response 200 (text/plain)

        This work by John Snow is licensed under CC0, go to https://creativecommons.org/publicdomain/zero/1.0/ for a copy of the license

+ Request (*/*)

+ Response 404 (application/json)

        {
            "message" : "No Object at this hash"
        }